Resolve if_not_else pedantic clippy lint
    error: unnecessary `!=` operation
       --> src/../jit/src/instance.rs:101:13
        |
    101 | /             if ffi::wasm_extern_kind(self.raw) != ffi::WASM_EXTERN_FUNC {
    102 | |                 None
    103 | |             } else {
    104 | |                 Some(FuncRef {
    ...   |
    107 | |                 })
    108 | |             }
        | |_____________^
        |
        = help: change to `==` and swap the blocks of the `if`/`else`
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#if_not_else
        = note: `-D clippy::if-not-else` implied by `-D clippy::pedantic`

    error: unnecessary `!=` operation
       --> src/../jit/src/instance.rs:114:13
        |
    114 | /             if ffi::wasm_extern_kind(self.raw) != ffi::WASM_EXTERN_MEMORY {
    115 | |                 None
    116 | |             } else {
    117 | |                 Some(MemoryRef {
    ...   |
    120 | |                 })
    121 | |             }
        | |_____________^
        |
        = help: change to `==` and swap the blocks of the `if`/`else`
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#if_not_else