Add Literal::c_string to proc-macro2
This was added in proc-macro2 1.80, but was missing from the patched version.
Newer versions of syn (>= 2.0.59) use this function, so any macro wanting to
use watt would fail with:

  error[E0599]: no function or associated item named `c_string` found for struct `proc_macro2::Literal` in the current scope
     --> /home/mwanzenboeck/.cargo/registry/src/index.crates.io-6f17d22bba15001f/syn-2.0.86/src/lit.rs:310:34
      |
  310 |         let mut token = Literal::c_string(value);
      |                                  ^^^^^^^^ function or associated item not found in `Literal`
      |

To fix this, add the necessary method, based on the same logic as the
Literal::byte_string method.